
[tool.black]
line-length = 120
target-version = ["py37"]

[tool.isort]
src_paths = ["dnd_utils", "tests"]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 120
multi_line_output = 3
lines_after_imports = 2